### ISSUE TITLE
TypeError TypeError: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by iridiumdev** [Aerbax/xmrExplorer#1]
When I follow all steps and run with my own Daemon, I get this error.

TypeError
TypeError: 'bool' object has no attribute '__getitem__'

**Comment by Aerbax** [comment]
That means that one of the functions returned "False" - which means that there was an exception.  

Make sure you have the daemon running and it's listening on the proper port.
And if this is not Monero, that it accepts the same RPC commands that Monero does.
